name: 'Acquia Drupal Startekit Content Model'
description: 'An content model provides Article, Event, Page, Person, Place content types.'
type: 'Starterkit addon'
recipes:
  - adsk_article
  - adsk_event
  - adsk_page
