name: 'Acquia Drupal Startekit Community'
description: 'The community starter kit will install Acquia Drupal Starterkit.'
type: 'Starterkit'
recipes:
  - adsk_admin_theme
  - adsk_security
  - core/recipes/core_recommended_front_end_theme
  - adsk_basic_html_editor
  - adsk_full_html_editor
install:
  - acquia_cms_toolbar
  - acquia_cms_tour
  - project_browser
config:
  import:
    olivero:
      - block.block.olivero_breadcrumbs
      - block.block.olivero_help
      - block.block.olivero_syndicate
  actions:
    olivero.settings:
      simple_config_update:
        base_primary_color: '#0a205a'
    project_browser.admin_settings:
      simple_config_update:
        allowed_projects:
          recipes:
            - adsk_Audio
            - adsk_community
            - adsk_content_model
            - adsk_dam
            - adsk_document
            - adsk_gdpr
            - adsk_headless
            - adsk_image
            - adsk_low_code
            - adsk_media
            - adsk_search
            - adsk_video
    system.site:
      simple_config_update:
        name: 'Acquia Drupal Starterkit'
        page.front: '/node'
    user.role.authenticated:
      grantPermissions:
        - 'access user profiles'
        - 'delete own files'
        - 'view own unpublished content'
    user.role.anonymous:
      grantPermissions:
        # We assume all published content should be accessible/
        - 'access content'
    user.settings:
      simple_config_update:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
