name: 'Acquia Drupal Startekit Headless'
description: "The headless starter kit preconfigures Drupal for serving structured, RESTful \ncontent to 3rd party content displays such as mobile apps, smart displays and \nfrontend driven websites (e.g. React or Next.js)."
type: 'Starterkit'
recipes:
  - adsk_community
install:
  # Contrib
  - acquia_cms_headless
config:
  actions:
    project_browser.admin_settings:
      simple_config_update:
        allowed_projects:
          recipes:
            - adsk_community
            - adsk_content_model
            - adsk_dam
            - adsk_gdpr
            - adsk_headless
            - adsk_media_model
            - adsk_search
